-- One-off cleanup: remove ghost products from the Styla catalog index.
--
-- WHY THIS EXISTS
-- Catalog sync used to only ever ADD rows, so products deleted in Shopify were
-- never removed from the index and kept being recommended. The permanent fix
-- (authoritative sync + prune) is in commit 0549191, but it runs on Vercel, so
-- it only takes effect after a deploy. This script clears the backlog now.
--
-- After the deploy, this script is obsolete -- a full sync does the same thing
-- automatically, and correctly, by comparing against the live Shopify catalog.
--
-- SAFETY
-- Deleting from catalog_products is non-destructive in the meaningful sense:
-- every row is derived data, regenerated by the next sync for any product that
-- still exists in Shopify. Nothing here touches size charts or merchant config.
--
-- Run the SELECT first and eyeball the list. Only then run the DELETE.

-- The products that still exist in the Shopify admin (verified 2026-08-08).
-- Includes the Gift Card, which lives under Gift cards rather than the
-- Products list, and "The Inventory Not Tracked Snowboard", which is still Active.
with live(external_id) as (values
  ('7740543991867'), -- Spanx Wide Leg Jeans
  ('7740543139899'), -- JJ's House Mateea
  ('7740541337659'), -- Azazie Novi
  ('7740531048507'), -- Ernest Navy checkered jacket
  ('7740499656763'), -- Straight-Fit Khaki Suit Blazer RW & Co
  ('7740415082555'), -- Tailor fit Black Suit RW & Co
  ('7740389621819'), -- Slim fit Suit RW & Co
  ('7697076977723'), -- The Inventory Not Tracked Snowboard
  ('7697077010491')  -- Gift Card
)

-- STEP 1 -- preview. Expect 11 rows: 10 snowboards + Selling Plans Ski Wax.
select c.external_id, c.title
from public.catalog_products c
where c.shop_domain = 'styla-test-store-l0e0shav.myshopify.com'
  and c.external_id not in (select external_id from live)
order by c.title;


-- STEP 2 -- delete. Uncomment and run once the preview above looks right.
--
-- with live(external_id) as (values
--   ('7740543991867'),('7740543139899'),('7740541337659'),('7740531048507'),
--   ('7740499656763'),('7740415082555'),('7740389621819'),('7697076977723'),
--   ('7697077010491')
-- )
-- delete from public.catalog_products c
-- where c.shop_domain = 'styla-test-store-l0e0shav.myshopify.com'
--   and c.external_id not in (select external_id from live);


-- STEP 3 -- confirm. Should return 9.
-- select count(*) from public.catalog_products
-- where shop_domain = 'styla-test-store-l0e0shav.myshopify.com';
