default_platform(:ios)

platform :ios do
  desc "Build and deploy Safari Extension to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    get_certificates(api_key: api_key)
    get_provisioning_profile(api_key: api_key, app_identifier: "com.styla.measure.safari")

    build_app(
      project: "./build-safari/STYLA Stylist/STYLA Stylist.xcodeproj",
      scheme: "STYLA Stylist",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key, skip_waiting_for_build_processing: true)
  end
end
