default_platform(:ios)

platform :ios do
  desc "Build and deploy Safari Extension to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    build_app(
      project: "./build-safari/STYLA Stylist.xcodeproj",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_testflight(api_key: api_key, skip_waiting_for_build_processing: true)
  end
end
