# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Styla Fit Engine"
client_id = "ae97233671ed9354af95498cd5c7fc62"
application_url = "https://real-candles-visit.loca.lt"
embedded = true

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[access_scopes]
scopes = "write_products,read_products,read_customers"

[auth]
redirect_urls = [
  "https://real-candles-visit.loca.lt/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
